%ECHO OFF
%ECHO Starting ECS System
PAUSE
%ECHO ECS Monitoring Console
START "MUSEUM ENVIRONMENTAL CONTROL SYSTEM CONSOLE" /NORMAL java ECSConsole %1
START "MUSEUM ENVIRONMENTAL CONTROL SYSTEM CONSOLE" /NORMAL java SecurityConsole %1

START "TEMPERATURE CONTROLLER CONSOLE" /MIN /NORMAL java TemperatureController %1

START "HUMIDITY CONTROLLER CONSOLE" /MIN /NORMAL java HumidityController %1
START "TEMPERATURE SENSOR CONSOLE" /MIN /NORMAL java TemperatureSensor %1

START "HUMIDITY SENSOR CONSOLE" /MIN /NORMAL java HumiditySensor %1
START "MUSEUM ENVIRONMENTAL CONTROL SYSTEM CONSOLE" /NORMAL java FireDetectionSensor %1

START "TEMPERATURE CONTROLLER CONSOLE" /MIN /NORMAL java FireAlarmController %1

START "TEMPERATURE CONTROLLER CONSOLE" /MIN /NORMAL java IntrusionSensor %1
START "HUMIDITY SENSOR CONSOLE" /MIN /NORMAL java SprinklerController %1
START "TEMPERATURE SENSOR CONSOLE" /MIN /NORMAL java IntrusionAlarmController %1